/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Trait = IDL.Text;
export const PersonalityType = IDL.Variant({
  'analytical' : IDL.Null,
  'creative' : IDL.Null,
  'introverted' : IDL.Null,
  'mysterious' : IDL.Null,
  'playful' : IDL.Null,
  'adventurous' : IDL.Null,
  'extroverted' : IDL.Null,
  'empathetic' : IDL.Null,
});
export const AvatarStyle = IDL.Variant({
  'illustrated' : IDL.Null,
  'anime' : IDL.Null,
  'realistic' : IDL.Null,
  'pixelArt' : IDL.Null,
  'watercolor' : IDL.Null,
});
export const CreateCharacterRequest = IDL.Record({
  'traits' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'personalityType' : PersonalityType,
  'personalityDescription' : IDL.Text,
  'avatarStyle' : AvatarStyle,
  'backgroundSnippet' : IDL.Text,
});
export const CharacterId = IDL.Nat;
export const Character = IDL.Record({
  'id' : CharacterId,
  'traits' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isPreseeded' : IDL.Bool,
  'personalityType' : PersonalityType,
  'personalityDescription' : IDL.Text,
  'avatarStyle' : AvatarStyle,
  'backgroundSnippet' : IDL.Text,
});
export const CharacterFilter = IDL.Record({
  'trait' : IDL.Opt(Trait),
  'personalityType' : IDL.Opt(PersonalityType),
  'searchQuery' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createCharacter' : IDL.Func([CreateCharacterRequest], [Character], []),
  'getCharacter' : IDL.Func([CharacterId], [IDL.Opt(Character)], ['query']),
  'listCharacters' : IDL.Func(
      [CharacterFilter],
      [IDL.Vec(Character)],
      ['query'],
    ),
  'listPersonalityTypes' : IDL.Func([], [IDL.Vec(PersonalityType)], ['query']),
  'listTraits' : IDL.Func([], [IDL.Vec(Trait)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Trait = IDL.Text;
  const PersonalityType = IDL.Variant({
    'analytical' : IDL.Null,
    'creative' : IDL.Null,
    'introverted' : IDL.Null,
    'mysterious' : IDL.Null,
    'playful' : IDL.Null,
    'adventurous' : IDL.Null,
    'extroverted' : IDL.Null,
    'empathetic' : IDL.Null,
  });
  const AvatarStyle = IDL.Variant({
    'illustrated' : IDL.Null,
    'anime' : IDL.Null,
    'realistic' : IDL.Null,
    'pixelArt' : IDL.Null,
    'watercolor' : IDL.Null,
  });
  const CreateCharacterRequest = IDL.Record({
    'traits' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'personalityType' : PersonalityType,
    'personalityDescription' : IDL.Text,
    'avatarStyle' : AvatarStyle,
    'backgroundSnippet' : IDL.Text,
  });
  const CharacterId = IDL.Nat;
  const Character = IDL.Record({
    'id' : CharacterId,
    'traits' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isPreseeded' : IDL.Bool,
    'personalityType' : PersonalityType,
    'personalityDescription' : IDL.Text,
    'avatarStyle' : AvatarStyle,
    'backgroundSnippet' : IDL.Text,
  });
  const CharacterFilter = IDL.Record({
    'trait' : IDL.Opt(Trait),
    'personalityType' : IDL.Opt(PersonalityType),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createCharacter' : IDL.Func([CreateCharacterRequest], [Character], []),
    'getCharacter' : IDL.Func([CharacterId], [IDL.Opt(Character)], ['query']),
    'listCharacters' : IDL.Func(
        [CharacterFilter],
        [IDL.Vec(Character)],
        ['query'],
      ),
    'listPersonalityTypes' : IDL.Func(
        [],
        [IDL.Vec(PersonalityType)],
        ['query'],
      ),
    'listTraits' : IDL.Func([], [IDL.Vec(Trait)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };