/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvatarStyle = { 'illustrated' : null } |
  { 'anime' : null } |
  { 'realistic' : null } |
  { 'pixelArt' : null } |
  { 'watercolor' : null };
export interface Character {
  'id' : CharacterId,
  'traits' : Array<Trait>,
  'name' : string,
  'createdAt' : bigint,
  'isPreseeded' : boolean,
  'personalityType' : PersonalityType,
  'personalityDescription' : string,
  'avatarStyle' : AvatarStyle,
  'backgroundSnippet' : string,
}
export interface CharacterFilter {
  'trait' : [] | [Trait],
  'personalityType' : [] | [PersonalityType],
  'searchQuery' : [] | [string],
}
export type CharacterId = bigint;
export interface CreateCharacterRequest {
  'traits' : Array<Trait>,
  'name' : string,
  'personalityType' : PersonalityType,
  'personalityDescription' : string,
  'avatarStyle' : AvatarStyle,
  'backgroundSnippet' : string,
}
export type PersonalityType = { 'analytical' : null } |
  { 'creative' : null } |
  { 'introverted' : null } |
  { 'mysterious' : null } |
  { 'playful' : null } |
  { 'adventurous' : null } |
  { 'extroverted' : null } |
  { 'empathetic' : null };
export type Trait = string;
export interface _SERVICE {
  'createCharacter' : ActorMethod<[CreateCharacterRequest], Character>,
  'getCharacter' : ActorMethod<[CharacterId], [] | [Character]>,
  'listCharacters' : ActorMethod<[CharacterFilter], Array<Character>>,
  'listPersonalityTypes' : ActorMethod<[], Array<PersonalityType>>,
  'listTraits' : ActorMethod<[], Array<Trait>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];