/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CharacterId = bigint;
export interface CreateCharacterRequest {
    traits: Array<Trait>;
    name: string;
    personalityType: PersonalityType;
    personalityDescription: string;
    avatarStyle: AvatarStyle;
    backgroundSnippet: string;
}
export interface CharacterFilter {
    trait?: Trait;
    personalityType?: PersonalityType;
    searchQuery?: string;
}
export interface Character {
    id: CharacterId;
    traits: Array<Trait>;
    name: string;
    createdAt: bigint;
    isPreseeded: boolean;
    personalityType: PersonalityType;
    personalityDescription: string;
    avatarStyle: AvatarStyle;
    backgroundSnippet: string;
}
export type Trait = string;
export enum AvatarStyle {
    illustrated = "illustrated",
    anime = "anime",
    realistic = "realistic",
    pixelArt = "pixelArt",
    watercolor = "watercolor"
}
export enum PersonalityType {
    analytical = "analytical",
    creative = "creative",
    introverted = "introverted",
    mysterious = "mysterious",
    playful = "playful",
    adventurous = "adventurous",
    extroverted = "extroverted",
    empathetic = "empathetic"
}
export interface backendInterface {
    createCharacter(req: CreateCharacterRequest): Promise<Character>;
    getCharacter(id: CharacterId): Promise<Character | null>;
    listCharacters(filter: CharacterFilter): Promise<Array<Character>>;
    listPersonalityTypes(): Promise<Array<PersonalityType>>;
    listTraits(): Promise<Array<Trait>>;
}
import type { AvatarStyle as _AvatarStyle, Character as _Character, CharacterFilter as _CharacterFilter, CharacterId as _CharacterId, CreateCharacterRequest as _CreateCharacterRequest, PersonalityType as _PersonalityType, Trait as _Trait } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCharacter(arg0: CreateCharacterRequest): Promise<Character> {
        if (this.processError) {
            try {
                const result = await this.actor.createCharacter(to_candid_CreateCharacterRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Character_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCharacter(to_candid_CreateCharacterRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Character_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacter(arg0: CharacterId): Promise<Character | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacter(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacter(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCharacters(arg0: CharacterFilter): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCharacters(to_candid_CharacterFilter_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCharacters(to_candid_CharacterFilter_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPersonalityTypes(): Promise<Array<PersonalityType>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPersonalityTypes();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPersonalityTypes();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTraits(): Promise<Array<Trait>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTraits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTraits();
            return result;
        }
    }
}
function from_candid_AvatarStyle_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarStyle): AvatarStyle {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Character_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Character): Character {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PersonalityType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalityType): PersonalityType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Character]): Character | null {
    return value.length === 0 ? null : from_candid_Character_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CharacterId;
    traits: Array<_Trait>;
    name: string;
    createdAt: bigint;
    isPreseeded: boolean;
    personalityType: _PersonalityType;
    personalityDescription: string;
    avatarStyle: _AvatarStyle;
    backgroundSnippet: string;
}): {
    id: CharacterId;
    traits: Array<Trait>;
    name: string;
    createdAt: bigint;
    isPreseeded: boolean;
    personalityType: PersonalityType;
    personalityDescription: string;
    avatarStyle: AvatarStyle;
    backgroundSnippet: string;
} {
    return {
        id: value.id,
        traits: value.traits,
        name: value.name,
        createdAt: value.createdAt,
        isPreseeded: value.isPreseeded,
        personalityType: from_candid_PersonalityType_n9(_uploadFile, _downloadFile, value.personalityType),
        personalityDescription: value.personalityDescription,
        avatarStyle: from_candid_AvatarStyle_n11(_uploadFile, _downloadFile, value.avatarStyle),
        backgroundSnippet: value.backgroundSnippet
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analytical: null;
} | {
    creative: null;
} | {
    introverted: null;
} | {
    mysterious: null;
} | {
    playful: null;
} | {
    adventurous: null;
} | {
    extroverted: null;
} | {
    empathetic: null;
}): PersonalityType {
    return "analytical" in value ? PersonalityType.analytical : "creative" in value ? PersonalityType.creative : "introverted" in value ? PersonalityType.introverted : "mysterious" in value ? PersonalityType.mysterious : "playful" in value ? PersonalityType.playful : "adventurous" in value ? PersonalityType.adventurous : "extroverted" in value ? PersonalityType.extroverted : "empathetic" in value ? PersonalityType.empathetic : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    illustrated: null;
} | {
    anime: null;
} | {
    realistic: null;
} | {
    pixelArt: null;
} | {
    watercolor: null;
}): AvatarStyle {
    return "illustrated" in value ? AvatarStyle.illustrated : "anime" in value ? AvatarStyle.anime : "realistic" in value ? AvatarStyle.realistic : "pixelArt" in value ? AvatarStyle.pixelArt : "watercolor" in value ? AvatarStyle.watercolor : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Character>): Array<Character> {
    return value.map((x)=>from_candid_Character_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersonalityType>): Array<PersonalityType> {
    return value.map((x)=>from_candid_PersonalityType_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AvatarStyle_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarStyle): _AvatarStyle {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CharacterFilter_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterFilter): _CharacterFilter {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCharacterRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCharacterRequest): _CreateCharacterRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PersonalityType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalityType): _PersonalityType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trait?: Trait;
    personalityType?: PersonalityType;
    searchQuery?: string;
}): {
    trait: [] | [_Trait];
    personalityType: [] | [_PersonalityType];
    searchQuery: [] | [string];
} {
    return {
        trait: value.trait ? candid_some(value.trait) : candid_none(),
        personalityType: value.personalityType ? candid_some(to_candid_PersonalityType_n3(_uploadFile, _downloadFile, value.personalityType)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    traits: Array<Trait>;
    name: string;
    personalityType: PersonalityType;
    personalityDescription: string;
    avatarStyle: AvatarStyle;
    backgroundSnippet: string;
}): {
    traits: Array<_Trait>;
    name: string;
    personalityType: _PersonalityType;
    personalityDescription: string;
    avatarStyle: _AvatarStyle;
    backgroundSnippet: string;
} {
    return {
        traits: value.traits,
        name: value.name,
        personalityType: to_candid_PersonalityType_n3(_uploadFile, _downloadFile, value.personalityType),
        personalityDescription: value.personalityDescription,
        avatarStyle: to_candid_AvatarStyle_n5(_uploadFile, _downloadFile, value.avatarStyle),
        backgroundSnippet: value.backgroundSnippet
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalityType): {
    analytical: null;
} | {
    creative: null;
} | {
    introverted: null;
} | {
    mysterious: null;
} | {
    playful: null;
} | {
    adventurous: null;
} | {
    extroverted: null;
} | {
    empathetic: null;
} {
    return value == PersonalityType.analytical ? {
        analytical: null
    } : value == PersonalityType.creative ? {
        creative: null
    } : value == PersonalityType.introverted ? {
        introverted: null
    } : value == PersonalityType.mysterious ? {
        mysterious: null
    } : value == PersonalityType.playful ? {
        playful: null
    } : value == PersonalityType.adventurous ? {
        adventurous: null
    } : value == PersonalityType.extroverted ? {
        extroverted: null
    } : value == PersonalityType.empathetic ? {
        empathetic: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarStyle): {
    illustrated: null;
} | {
    anime: null;
} | {
    realistic: null;
} | {
    pixelArt: null;
} | {
    watercolor: null;
} {
    return value == AvatarStyle.illustrated ? {
        illustrated: null
    } : value == AvatarStyle.anime ? {
        anime: null
    } : value == AvatarStyle.realistic ? {
        realistic: null
    } : value == AvatarStyle.pixelArt ? {
        pixelArt: null
    } : value == AvatarStyle.watercolor ? {
        watercolor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
